FROM python:3.11-slim

WORKDIR /workspace

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY frontend /workspace/frontend

EXPOSE 8501

CMD streamlit run frontend/streamlit_app.py --server.port ${PORT:-8501} --server.address 0.0.0.0
